### ISSUE TITLE
Error reading [IFTSAI][D:99A:UN] message

### ISSUE THREAD

**Issue by rychoo2** [smooks/unedifact#31]
Hello, I am trying to use this library to parse D99A message running following kotlin code:
```
val file = this::class.java.classLoader.getResource("EDIFACT_D99A_IFTSAI.txt").openStream()
val factory: D99AInterchangeFactory = D99AInterchangeFactory.getInstance()
val interchange = factory.fromUNEdifact(file)
```

I am getting an error:

> Caused by: org.milyn.edisax.EDIParseException: EDI message processing failed [IFTSAI][D:99A:UN].  Reached end of mapping model but there are more EDI segments in the incoming message.  Read 220 segment(s). Current EDI segment is [LOC+7+JPHBK:139:6]
	at org.milyn.edisax.EDIParser.parse(EDIParser.java:434)
	at org.milyn.edisax.EDIParser.parse(EDIParser.java:410)
	at org.milyn.edisax.unedifact.handlers.UNHHandler.process(UNHHandler.java:97)
	at org.milyn.edisax.unedifact.handlers.UNBHandler.process(UNBHandler.java:75)
	at org.milyn.edisax.unedifact.UNEdifactInterchangeParser.parse(UNEdifactInterchangeParser.java:114)
	at org.milyn.smooks.edi.unedifact.UNEdifactReader.parse(UNEdifactReader.java:75)
	at org.milyn.delivery.sax.SAXParser.parse(SAXParser.java:76)
	at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:86)

I am unable to find what could be wrong with the message and why it incorrectly detects the end of mapping before 'LOC+7+JPHBK:139:6' segment.
The message is:

> UNA:+.? 'UNB+UNOA:2+XXXXXXXXXXX+YYYYYY+190106:0100+182182'UNH+1+IFTSAI:D:99A:UN'BGM+TS2+002429+9'DTM+137:201901060100:203'FTX+AAI+++BUS ARRIVAL/DEPARTURE SCHEDULE'FTX+TRA+++EC1'TDT+20+224632+1++HLCU:172:20+++9424900:146:11:MOL MAGNIFICENCE:MH'RFF+VON:051E'LOC+9+JPUKB:139:6'DTM+180:201902191630:203'DTM+141:201902191630:203'DTM+133:201902210600:203'LOC+11+CNNGB:139:6'DTM+180:201902230600:203'DTM+411:201902230600:203'DTM+141:201902230600:203'DTM+132:201902230600:203'LOC+11+CNSHA:139:6'DTM+180:201902240800:203'DTM+411:201902240800:203'DTM+141:201902240800:203'DTM+132:201902240800:203'DTM+133:201902250300:203'LOC+7+CNYIB:139:6'DTM+132:20190313:102'LOC+7+CNCKG:139:6'DTM+132:20190312:102'LOC+7+CNLUZ:139:6'DTM+132:20190312:102'LOC+7+CNFLG:139:6'DTM+132:20190309:102'LOC+7+CNWZH:139:6'DTM+132:20190308:102'LOC+7+CNYYA:139:6'DTM+132:20190306:102'LOC+7+CNJGZ:139:6'DTM+132:20190306:102'LOC+7+CNCSX:139:6'DTM+132:20190306:102'LOC+7+CNCGD:139:6'DTM+132:20190306:102'LOC+7+CNWUH:139:6'DTM+132:20190305:102'LOC+7+CNYIC:139:6'DTM+132:20190304:102'LOC+7+CNYZH:139:6'DTM+132:20190303:102'LOC+7+CNJIU:139:6'DTM+132:20190303:102'LOC+7+CNMAA:139:6'DTM+132:20190303:102'LOC+7+CNTZO:139:6'DTM+132:20190303:102'LOC+7+CNWHI:139:6'DTM+132:20190303:102'LOC+7+CNKHN:139:6'DTM+132:20190303:102'LOC+7+CNHFE:139:6'DTM+132:20190303:102'LOC+7+CNCZX:139:6'DTM+132:20190303:102'LOC+7+CNAQG:139:6'DTM+132:20190302:102'LOC+7+CNZJG:139:6'DTM+132:20190302:102'LOC+7+CNHSI:139:6'DTM+132:20190302:102'LOC+7+CNTAC:139:6'DTM+132:20190302:102'LOC+7+CNNTG:139:6'DTM+132:20190302:102'LOC+7+CNJIA:139:6'DTM+132:20190302:102'LOC+7+CNCGS:139:6'DTM+132:20190302:102'LOC+7+CNCHI:139:6'DTM+132:20190301:102'LOC+7+CNZHE:139:6'DTM+132:20190301:102'LOC+7+CNNKG:139:6'DTM+132:20190301:102'LOC+7+CNTOL:139:6'DTM+132:20190301:102'LOC+7+CNANJ:139:6'DTM+132:20190228:102'LOC+7+CNDEI:139:6'DTM+132:20190227:102'LOC+11+KRPUS:139:6'DTM+180:201902260200:203'DTM+411:201902260200:203'DTM+141:201902261200:203'DTM+132:201902261200:203'DTM+133:201902270600:203'LOC+7+USPEF:139:6'DTM+132:20190328:102'LOC+7+USBOS:139:6'DTM+132:20190324:102'LOC+7+RUMAG:139:6'DTM+132:20190314:102'LOC+7+CNRZH:139:6'DTM+132:20190307:102'LOC+7+CNSHD:139:6'DTM+132:20190306:102'LOC+7+CNJTG:139:6'DTM+132:20190306:102'LOC+7+CNJNZ:139:6'DTM+132:20190305:102'LOC+7+JPHIC:139:6'DTM+132:20190305:102'LOC+7+CNYIK:139:6'DTM+132:20190305:102'LOC+7+CNLKU:139:6'DTM+132:20190305:102'LOC+7+CNSHP:139:6'DTM+132:20190305:102'LOC+7+CNDDG:139:6'DTM+132:20190305:102'LOC+7+CNWZO:139:6'DTM+132:20190304:102'LOC+7+JPTHS:139:6'DTM+132:20190304:102'LOC+7+JPMUR:139:6'DTM+132:20190304:102'LOC+7+JPKUH:139:6'DTM+132:20190304:102'LOC+7+JPHHE:139:6'DTM+132:20190304:102'LOC+7+CNWEI:139:6'DTM+132:20190304:102'LOC+7+CNZPU:139:6'DTM+132:20190303:102'LOC+7+RUKOR:139:6'DTM+132:20190303:102'LOC+7+JPKNZ:139:6'DTM+132:20190303:102'LOC+7+JPONA:139:6'DTM+132:20190303:102'LOC+7+JPISI:139:6'DTM+132:20190303:102'LOC+7+JPKIJ:139:6'DTM+132:20190303:102'LOC+7+JPKCZ:139:6'DTM+132:20190303:102'LOC+7+JPAXT:139:6'DTM+132:20190303:102'LOC+7+JPHKD:139:6'DTM+132:20190303:102'LOC+7+CNHME:139:6'DTM+132:20190303:102'LOC+7+RUVVO:139:6'DTM+132:20190302:102'LOC+7+RUVYP:139:6'DTM+132:20190302:102'LOC+7+JPIYM:139:6'DTM+132:20190302:102'LOC+7+JPTAK:139:6'DTM+132:20190302:102'LOC+7+JPTOY:139:6'DTM+132:20190302:102'LOC+7+JPTRG:139:6'DTM+132:20190302:102'LOC+7+JPSKT:139:6'DTM+132:20190302:102'LOC+7+JPOIT:139:6'DTM+132:20190302:102'LOC+7+JPNGS:139:6'DTM+132:20190302:102'LOC+7+JPNGO:139:6'DTM+132:20190302:102'LOC+7+JPNAO:139:6'DTM+132:20190302:102'LOC+7+JPIMB:139:6'DTM+132:20190302:102'LOC+7+JPHSM:139:6'DTM+132:20190302:102'LOC+7+CNYNT:139:6'DTM+132:20190302:102'LOC+7+JPABU:139:6'DTM+132:20190302:102'LOC+7+CNTXG:139:6'DTM+132:20190302:102'LOC+7+JPHMD:139:6'DTM+132:20190301:102'LOC+7+JPMYJ:139:6'DTM+132:20190301:102'LOC+7+JPSMN:139:6'DTM+132:20190301:102'LOC+7+JPUBJ:139:6'DTM+132:20190301:102'LOC+7+JPYOK:139:6'DTM+132:20190301:102'LOC+7+JPYKK:139:6'DTM+132:20190301:102'LOC+7+JPYAT:139:6'DTM+132:20190301:102'LOC+7+JPTKS:139:6'DTM+132:20190301:102'LOC+7+JPTKY:139:6'DTM+132:20190301:102'LOC+7+JPSEN:139:6'DTM+132:20190301:102'LOC+7+JPOSA:139:6'DTM+132:20190301:102'LOC+7+JPNAN:139:6'DTM+132:20190301:102'LOC+7+JPIWK:139:6'DTM+132:20190301:102'LOC+7+JPMAI:139:6'DTM+132:20190301:102'LOC+7+CNDLC:139:6'DTM+132:20190301:102'LOC+7+CNTAO:139:6'DTM+132:20190228:102'LOC+7+JPKMJ:139:6'DTM+132:20190228:102'LOC+7+JPSHS:139:6'DTM+132:20190228:102'LOC+7+JPHIJ:139:6'DTM+132:20190228:102'LOC+7+JPHBK:139:6'DTM+132:20190228:102'LOC+7+KRINC:139:6'DTM+132:20190227:102'LOC+11+JPTYO:139:6'DTM+180:201902281630:203'DTM+141:201902281630:203'DTM+132:201903011300:203'LOC+11+PAMIT:139:6'DTM+180:201903181700:203'DTM+411:201903181700:203'DTM+141:201903181700:203'DTM+132:201903191900:203'DTM+133:201903201700:203'LOC+7+LCCAS:139:6'DTM+132:20190408:102'LOC+7+MXPGO:139:6'DTM+132:20190406:102'LOC+7+MXVER:139:6'DTM+132:20190401:102'LOC+7+MXATM:139:6'DTM+132:20190331:102'LOC+7+GYGEO:139:6'DTM+132:20190328:102'LOC+7+HNPCR:139:6'DTM+132:20190325:102'LOC+7+PRSJU:139:6'DTM+132:20190325:102'LOC+7+AWORJ:139:6'DTM+132:20190324:102'LOC+7+GTSTC:139:6'DTM+132:20190324:102'LOC+7+HTPAP:139:6'DTM+132:20190323:102'LOC+7+VEMAR:139:6'DTM+132:20190323:102'LOC+7+VEGUT:139:6'DTM+132:20190323:102'LOC+7+VEGUA:139:6'DTM+132:20190322:102'LOC+7+CWWIL:139:6'DTM+132:20190322:102'LOC+7+CRLIO:139:6'DTM+132:20190320:102'LOC+11+USSAV:139:6'DTM+180:201903221600:203'DTM+411:201903221600:203'DTM+141:201903221600:203'DTM+132:201903241700:203'DTM+133:201903251800:203'LOC+7+USMOB:139:6'DTM+132:20190416:102'LOC+11+USJAX:139:6'DTM+180:201903251600:203'DTM+411:201903251600:203'DTM+141:201903251600:203'DTM+132:201903261300:203'LOC+11+USCHS:139:6'DTM+180:201903261600:203'DTM+411:201903261600:203'DTM+141:201903261600:203'DTM+132:201903271900:203'LOC+11+USORF:139:6'DTM+180:201903291600:203'DTM+411:201903291600:203'DTM+141:201903291600:203'DTM+132:201903300700:203'DTM+133:201903310300:203'LOC+7+USBAL:139:6'DTM+132:20190331:102'UNT+289+1'UNZ+1+289'

The message was extracted from a larger file so it might not correct about UNZ segment.
I would appreciate any help.

**Comment by manish-in-java** [comment]
The posted message is invalid. [EDI Notepad](https://www.liaison.com/products/integrate/edi-notepad/) shows the following errors:

1. The message control numbers in `UNA` and `UNZ` segments do not match (`182182` in `UNA` and `289` in `UNZ`).
1. The `BGM` segment has the invalid code `TS2`. Please review the [description of the BGM segment](http://www.stylusstudio.com/edifact/D99A/BGM_.htm) for the valid codes for that segment.

The following sample message, taken from [this document](http://www.tslines.com:8080/download/5_Equipment%20Control(English)/PSAA%20Guidelines%20IFTSAI.pdf) is validated successfully by EDI Notepad, after changing `TS2` to an acceptable value.

```
UNB+UNOA:2+100300+101311+021102:1148+1103131'UNH+90062700464801+IFTSAI:D:99B:UN:SMDG10+IFTSAI90062700464801'
BGM+99+IFTSAI90062700464801+9'
DTM+137:200211021149:203'
FTX+TRA++06:ZZZ:ZZZ+MSC EAST MED'
TDT+20+35R+1+8+MSC:172:20+++L7359852:ZZZ::MSC ALICE:PA'
RFF+VM:3FUV5'
RFF+VON:006270'
LOC+11+BEANR:139:6+730:266:ZZZ'
LOC+9+USNYC:139:6'
DTM+232:200211300000:203'
LOC+9+USMIA:139:6'
DTM+232:200211300000:203'
LOC+9+GBFXT:139:6'
DTM+232:200211300000:203'
NAD+CA+MSC:160:20'
UNT+16+90062700464801'
UNZ+1+1103131'
```

Please make sure that EDI messages are valid before attempting to parse them with Smooks.

**Comment by rychoo2** [comment]
Hi, Thanks for your comments. I updated the message as per your suggestions but the error is still the same.

After a little debugging I found out that the error is caused by the fact that segment group 5 contains more that 99 segments and in the IFTSAI mapping there is a hard limit of 99:
`<medi:segmentGroup maxOccurs="99" minOccurs="0" xmltag="Segment_group_5">`

After removing excessive segments smooks correctly parsed the message regardless of other errors.

Could you point out where this limit is specified in the EDIFACT docs? 
I receive those messages from external provider so I doubt that they would fix it. Is there any recommended way to override or disregard those limits?

**Comment by manish-in-java** [comment]
Can you clarify which file are you referring to, and what version of Smooks are you using?

**Comment by rychoo2** [comment]
I am using latest version 1.7.1 with org.milyn.edi.unedifact:d99a-mapping:1.7.1.0.
Inside [d99a-mapping-1.7.1.0.jar](https://search.maven.org/remotecontent?filepath=org/milyn/edi/unedifact/d99a-mapping/1.7.1.0/d99a-mapping-1.7.1.0.jar) there is IFTSAI.xml mapping provided:

```xml
<medi:edimap xmlns:medi="http://www.milyn.org/schema/edi-message-mapping-1.5.xsd">
    <medi:import namespace="UN" resource="__modelset_definitions.xml"/>
    <medi:description name="IFTSAI" namespace="urn:org.milyn.edi.unedifact:un:d99a:iftsai" version="D:99A:UN"/>
    <medi:delimiters component=":" escape="?" field="+" segment="'!$" sub-component="~"/>
    <medi:segments xmltag="IFTSAI">
        <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Beginning of message" nodeTypeRef="UN:BGM" segcode="BGM" truncatable="true" xmltag="BGM">
            <medi:documentation>BGM,
       A segment to indicate the type and function of the message and
       to transmit the identifying number.</medi:documentation>
        </medi:segment>
        <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Date/time/period" nodeTypeRef="UN:DTM" segcode="DTM" truncatable="true" xmltag="DTM">
            <medi:documentation>DTM,
       A segment to indicate date(s) and time(s) applying to the whole
       message.</medi:documentation>
        </medi:segment>
        <medi:segment ignoreUnmappedFields="false" maxOccurs="99" minOccurs="0" name="Free text" nodeTypeRef="UN:FTX" segcode="FTX" truncatable="true" xmltag="FTX">
            <medi:documentation>FTX,
       A segment to specify free form or processable supplementary
       information. In computer-to-computer exchanges free form text
       will normally require the receiver to process this segment
       manually.</medi:documentation>
        </medi:segment>
        <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="0" name="General indicator" nodeTypeRef="UN:GIS" segcode="GIS" truncatable="true" xmltag="GIS">
            <medi:documentation>GIS,
       A segment to provide a general indicator relating to the whole
       message, such as urgency.</medi:documentation>
        </medi:segment>
        <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_1">
            <medi:documentation>Segment group 1:
       A group of segments to specify the document or message to which
       the current message relates, and related date and time.</medi:documentation>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Reference" nodeTypeRef="UN:RFF" segcode="RFF" truncatable="true" xmltag="RFF">
                <medi:documentation>RFF,
          A segment to identify a reference which applies to the
          entire message, e.g. reference to previous message.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Date/time/period" nodeTypeRef="UN:DTM" segcode="DTM" truncatable="true" xmltag="DTM">
                <medi:documentation>DTM,
          A segment to indicate date and time relating to the
          reference.</medi:documentation>
            </medi:segment>
        </medi:segmentGroup>
        <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_2">
            <medi:documentation>Segment group 2:
       A group of segments to identify the routing and date of the
       schedule or availability information.</medi:documentation>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Place/location identification" nodeTypeRef="UN:LOC" segcode="LOC" truncatable="true" xmltag="LOC">
                <medi:documentation>LOC,
          A segment to identify a location, e.g. place of
          departure/arrival.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Date/time/period" nodeTypeRef="UN:DTM" segcode="DTM" truncatable="true" xmltag="DTM">
                <medi:documentation>DTM,
          A segment to indicate date(s) and time(s) related to the
          location.</medi:documentation>
            </medi:segment>
        </medi:segmentGroup>
        <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_3">
            <medi:documentation>Segment group 3:
       A group of segments to define requested or available equipment.</medi:documentation>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Equipment details" nodeTypeRef="UN:EQD" segcode="EQD" truncatable="true" xmltag="EQD">
                <medi:documentation>EQD,
          A segment to specify requested or available equipment and
          equipment size and type.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Number of units" nodeTypeRef="UN:EQN" segcode="EQN" truncatable="true" xmltag="EQN">
                <medi:documentation>EQN,
          A segment to specify the number of requested or available
          pieces of equipment.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Measurements" nodeTypeRef="UN:MEA" segcode="MEA" truncatable="true" xmltag="MEA">
                <medi:documentation>MEA,
          A segment to specify measurements, other than dimensions,
          associated with equipment, in terms of capacity.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Dimensions" nodeTypeRef="UN:DIM" segcode="DIM" truncatable="true" xmltag="DIM">
                <medi:documentation>DIM,
          A segment to specify dimensions applicable to equipment.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Free text" nodeTypeRef="UN:FTX" segcode="FTX" truncatable="true" xmltag="FTX">
                <medi:documentation>FTX,
          A segment to specify free form or processable supplementary
          information associated with the equipment.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Reference" nodeTypeRef="UN:RFF" segcode="RFF" truncatable="true" xmltag="RFF">
                <medi:documentation>RFF,
          A segment to specify a reference number to equipment.</medi:documentation>
            </medi:segment>
        </medi:segmentGroup>
        <medi:segmentGroup maxOccurs="999" minOccurs="0" xmltag="Segment_group_4">
            <medi:documentation>Segment group 4:
       A group of segments to specify the schedule or availability
       selection criteria and to detail the schedule or availability
       information being provided.</medi:documentation>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Details of transport" nodeTypeRef="UN:TDT" segcode="TDT" truncatable="true" xmltag="TDT">
                <medi:documentation>TDT,
          A segment to indicate information related to the mode and
          means of transport, eg. specific conveyance/carrier.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Date/time/period" nodeTypeRef="UN:DTM" segcode="DTM" truncatable="true" xmltag="DTM">
                <medi:documentation>DTM,
          A segment to indicate date(s) and time(s), e.g. earliest
          departure date/time, latest arrival date/time.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Transport service requirements" nodeTypeRef="UN:TSR" segcode="TSR" truncatable="true" xmltag="TSR">
                <medi:documentation>TSR,
          A segment to identify contract, conditions of carriage,
          services and priority requirements.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Reference" nodeTypeRef="UN:RFF" segcode="RFF" truncatable="true" xmltag="RFF">
                <medi:documentation>RFF,
          A segment to provide a reference related to the transport
          details, such as the published line or route number.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Free text" nodeTypeRef="UN:FTX" segcode="FTX" truncatable="true" xmltag="FTX">
                <medi:documentation>FTX,
          A segment to specify free form or processable supplementary
          information related to the means of transport.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="99" minOccurs="0" name="Equipment details" nodeTypeRef="UN:EQD" segcode="EQD" truncatable="true" xmltag="EQD">
                <medi:documentation>EQD,
          A segment to identify the equipment requested/available.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Quantity" nodeTypeRef="UN:QTY" segcode="QTY" truncatable="true" xmltag="QTY">
                <medi:documentation>QTY,
          A segment to indicate a quantity, e.g. number of
          intermediate stops.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Measurements" nodeTypeRef="UN:MEA" segcode="MEA" truncatable="true" xmltag="MEA">
                <medi:documentation>MEA,
          A segment to indicate weight and/or volume selection
          criteria, e.g. minimum weight.</medi:documentation>
            </medi:segment>
            <medi:segmentGroup maxOccurs="99" minOccurs="0" xmltag="Segment_group_5">
                <medi:documentation>Segment group 5:
          A group of segments to identify the routing(s) and indicate
          corresponding date(s) and time(s).</medi:documentation>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Place/location identification" nodeTypeRef="UN:LOC" segcode="LOC" truncatable="true" xmltag="LOC">
                    <medi:documentation>LOC,
             A segment to identify a location, e.g. place of
             departure/arrival.</medi:documentation>
                </medi:segment>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Date/time/period" nodeTypeRef="UN:DTM" segcode="DTM" truncatable="true" xmltag="DTM">
                    <medi:documentation>DTM,
             A segment to indicate date(s) and time(s) related to the
             location, e.g. date/time of scheduled departure/arrival.</medi:documentation>
                </medi:segment>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Reference" nodeTypeRef="UN:RFF" segcode="RFF" truncatable="true" xmltag="RFF">
                    <medi:documentation>RFF,
             A segment to provide a reference related to the location,
             such as the platform number at the place of departure.</medi:documentation>
                </medi:segment>
            </medi:segmentGroup>
        </medi:segmentGroup>
        <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_6">
            <medi:documentation>Segment group 6:
       A group of segments to indicate all parties involved in the
       transaction and relevant locations, contacts and communication
       channels.</medi:documentation>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Name and address" nodeTypeRef="UN:NAD" segcode="NAD" truncatable="true" xmltag="NAD">
                <medi:documentation>NAD,
          A segment to identify the party's name, address and
          function.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Place/location identification" nodeTypeRef="UN:LOC" segcode="LOC" truncatable="true" xmltag="LOC">
                <medi:documentation>LOC,
          A segment to identify a place/location/sub-location and
          where relevant the function. The present location must be
          associated with the relevant party.</medi:documentation>
            </medi:segment>
            <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_7">
                <medi:documentation>Segment group 7:
          A group of segments to identify a contact and its
          communication channels, related to the party.</medi:documentation>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Contact information" nodeTypeRef="UN:CTA" segcode="CTA" truncatable="true" xmltag="CTA">
                    <medi:documentation>CTA,
             A segment to identify a person or department within a
             party.</medi:documentation>
                </medi:segment>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Communication contact" nodeTypeRef="UN:COM" segcode="COM" truncatable="true" xmltag="COM">
                    <medi:documentation>COM,
             A segment to identify the communication numbers of person
             or department to whom communication should be directed.</medi:documentation>
                </medi:segment>
            </medi:segmentGroup>
        </medi:segmentGroup>
        <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_8">
            <medi:documentation>Segment group 8:
       A group of segments to describe the goods items for which
       schedule or availability is requested/provided.</medi:documentation>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Goods item details" nodeTypeRef="UN:GID" segcode="GID" truncatable="true" xmltag="GID">
                <medi:documentation>GID,
          A segment to identify the goods item. A goods item can be
          identified by up to three levels of packaging within this
          segment.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Handling instructions" nodeTypeRef="UN:HAN" segcode="HAN" truncatable="true" xmltag="HAN">
                <medi:documentation>HAN,
          A segment to specify handling instructions relating to the
          goods item.</medi:documentation>
            </medi:segment>
            <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Free text" nodeTypeRef="UN:FTX" segcode="FTX" truncatable="true" xmltag="FTX">
                <medi:documentation>FTX,
          A segment to specify free form or processable information
          relating to the goods item.</medi:documentation>
            </medi:segment>
            <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_9">
                <medi:documentation>Segment group 9:
          A group of segments to identify and describe the goods.</medi:documentation>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Nature of cargo" nodeTypeRef="UN:GDS" segcode="GDS" truncatable="true" xmltag="GDS">
                    <medi:documentation>GDS,
             A segment to describe the nature of cargo.</medi:documentation>
                </medi:segment>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Free text" nodeTypeRef="UN:FTX" segcode="FTX" truncatable="true" xmltag="FTX">
                    <medi:documentation>FTX,
             A segment to describe the goods in free form.</medi:documentation>
                </medi:segment>
            </medi:segmentGroup>
            <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_10">
                <medi:documentation>Segment group 10:
          A group of segments to specify measurements applicable to
          the goods item.</medi:documentation>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Measurements" nodeTypeRef="UN:MEA" segcode="MEA" truncatable="true" xmltag="MEA">
                    <medi:documentation>MEA,
             A segment to specify measurements, other than dimensions,
             applicable to the goods item.</medi:documentation>
                </medi:segment>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Number of units" nodeTypeRef="UN:EQN" segcode="EQN" truncatable="true" xmltag="EQN">
                    <medi:documentation>EQN,
             A segment to specify the number of equipment units to
             which the measurement applies.</medi:documentation>
                </medi:segment>
            </medi:segmentGroup>
            <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_11">
                <medi:documentation>Segment group 11:
          A group of segments to specify dimensions applicable to the
          goods item.</medi:documentation>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Dimensions" nodeTypeRef="UN:DIM" segcode="DIM" truncatable="true" xmltag="DIM">
                    <medi:documentation>DIM,
             A segment to specify dimensions applicable to the goods
             item.</medi:documentation>
                </medi:segment>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Number of units" nodeTypeRef="UN:EQN" segcode="EQN" truncatable="true" xmltag="EQN">
                    <medi:documentation>EQN,
             A segment to specify the number of equipment units to
             which the given dimensions apply.</medi:documentation>
                </medi:segment>
            </medi:segmentGroup>
            <medi:segmentGroup maxOccurs="9" minOccurs="0" xmltag="Segment_group_12">
                <medi:documentation>Segment group 12:
          A group of segments to specify dangerous goods details
          related to the goods item.</medi:documentation>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="1" minOccurs="1" name="Dangerous goods" nodeTypeRef="UN:DGS" segcode="DGS" truncatable="true" xmltag="DGS">
                    <medi:documentation>DGS,
             A segment to specify the class of dangerous goods,
             packing group, etc.</medi:documentation>
                </medi:segment>
                <medi:segment ignoreUnmappedFields="false" maxOccurs="9" minOccurs="0" name="Free text" nodeTypeRef="UN:FTX" segcode="FTX" truncatable="true" xmltag="FTX">
                    <medi:documentation>FTX,
             A segment to specify the dangerous goods technical name
             and any other additional dangerous goods information.</medi:documentation>
                </medi:segment>
            </medi:segmentGroup>
        </medi:segmentGroup>
    </medi:segments>
</medi:edimap>
```

**Comment by manish-in-java** [comment]
The restriction on the number of Segment 5 segment groups is as per the [D99A specification](https://service.unece.org/trade/untdid/d99a/trmd/iftsai_s.htm) for the `IFTSAI` message. A more readable version of the specification is available [here](www.stylusstudio.com/edifact/D99A/IFTSAI.htm#part4.3).

Do note that all EDIFACT specifications are available from the UNECE website so when in doubt, please consult the appropriate EDIFACT release.

It seems that the message provided to you is invalid, as per the specification.

Having said that, you have two workarounds at your disposal:

1. If your sender can switch to [release D0A](https://www.unece.org/fileadmin/DAM/trade/untdid/d04a/trmd/iftsai_c.htm), that release allows a maximum of 999 segment 5 segment groups.
1. You can download the source code from this repository, unzip the D99A specification, change the specification as per your requirement (change maximum limit for segment 5 segment groups from 99 to a very large value), zip the specification, build binaries, and use them for your project.

**Comment by rychoo2** [comment]
Makes sense, many thanks for your help.
